{% set name = "spotipy" %}
{% set version = "2.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dfafe08239daae6c16faa68f60b5775d40c4110725e1a7c545ad4c7fb66d4e8

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - redis-py >=3.5.3
    - requests >=2.25.0
    - six >=1.15.0
    - urllib3 >=1.26.0

test:
  imports:
    - spotipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://spotipy.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A light weight Python library for the Spotify Web API
  doc_url: http://spotipy.readthedocs.org/
  dev_url: https://github.com/plamere/spotipy/

extra:
  recipe-maintainers:
    - captivus
